
GET http://localhost:3000/api/v1/categories HTTP/1.1

###

GET https://example.com/topics/1 HTTP/1.1

###

POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "Test6",
    "email": "test6@gmail.com"
}

###

PUT http://localhost:3000/api/v1/categories/612e8ea36f7495239d901a3e HTTP/1.1
content-type: application/json

{
    "name": "Pc Gamer 3",
    "icon": "fa fa-heart",
    "color": "#255825"
}